package com.dsetanzania.dse.helperClasses.livedata_classes;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.7.8
//
// Created by Quasar Development 
//
//---------------------------------------------------





import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;

import java.util.ArrayList;
import java.util.List;


public class OOUdefault_AtsWebFeedService
{
    interface OOUIWcfMethod
    {
        OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

        Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception;
    }

    String url="http://ht.ddnss.ch:6080/livefeedCustodian/FeedWebService.svc";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders= new ArrayList< HeaderProperty>();
    public boolean enableLogging;

    OOUIServiceEvents callback;
    public OOUdefault_AtsWebFeedService(String s){}

    public OOUdefault_AtsWebFeedService (OOUIServiceEvents callback)
    {
        this.callback = callback;
    }
    public OOUdefault_AtsWebFeedService(OOUIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public OOUdefault_AtsWebFeedService(OOUIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }

    protected OOUExtendedSoapSerializationEnvelope createEnvelope()
    {
        OOUExtendedSoapSerializationEnvelope envelope= new OOUExtendedSoapSerializationEnvelope(OOUExtendedSoapSerializationEnvelope.VER11);
            return envelope;
    }

    protected List sendRequest(String methodName, OOUExtendedSoapSerializationEnvelope envelope, Transport transport , com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile )throws Exception
    {
        if(transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE )
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
        else
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
    }

    Object getResult(Class destObj, Object source, String resultName, OOUExtendedSoapSerializationEnvelope __envelope) throws Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) 
            {
                Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }

        return null;
    }

    
    public OOUArrayOfSecurityLivePrice LiveMarketPrices( ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OOUArrayOfSecurityLivePrice)execute(new OOUIWcfMethod()
        {
            @Override
            public OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OOUExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "LiveMarketPrices");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object __result)throws Exception {
                return (OOUArrayOfSecurityLivePrice)getResult(OOUArrayOfSecurityLivePrice.class,__result,"LiveMarketPricesResult",__envelope);
            }
        },"http://tempuri.org/AtsWebFeedService/LiveMarketPrices",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OOUOperationResult< OOUArrayOfSecurityLivePrice>> LiveMarketPricesAsync()
    {
        return executeAsync(new OOUFunctions.IFunc< OOUArrayOfSecurityLivePrice>() {
            public OOUArrayOfSecurityLivePrice Func() throws Exception {
                return LiveMarketPrices( );
            }
        },"LiveMarketPrices");
    }
    
    public OOUArrayOfSecurityLivePrice DelayedMarketPrices( ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OOUArrayOfSecurityLivePrice)execute(new OOUIWcfMethod()
        {
            @Override
            public OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OOUExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "DelayedMarketPrices");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object __result)throws Exception {
                return (OOUArrayOfSecurityLivePrice)getResult(OOUArrayOfSecurityLivePrice.class,__result,"DelayedMarketPricesResult",__envelope);
            }
        },"http://tempuri.org/AtsWebFeedService/DelayedMarketPrices",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OOUOperationResult< OOUArrayOfSecurityLivePrice>> DelayedMarketPricesAsync()
    {
        return executeAsync(new OOUFunctions.IFunc< OOUArrayOfSecurityLivePrice>() {
            public OOUArrayOfSecurityLivePrice Func() throws Exception {
                return DelayedMarketPrices( );
            }
        },"DelayedMarketPrices");
    }
    
    public OOUArrayOfInstrumentTurnoverFeed TurnoverVolumeDeals(final java.util.Date FromDate,final java.util.Date ToDate,final String AssetClass,final String SecurityCode,final Integer MarketCode,final Integer DataPeriod ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OOUArrayOfInstrumentTurnoverFeed)execute(new OOUIWcfMethod()
        {
            @Override
            public OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OOUExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "TurnoverVolumeDeals");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="FromDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(FromDate!=null?OOUHelper.getDateTimeFormat().format(FromDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="ToDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ToDate!=null?OOUHelper.getDateTimeFormat().format(ToDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="AssetClass";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(AssetClass!=null?AssetClass:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="SecurityCode";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(SecurityCode!=null?SecurityCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="MarketCode";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(MarketCode!=null?MarketCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="DataPeriod";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(DataPeriod!=null?DataPeriod:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object __result)throws Exception {
                return (OOUArrayOfInstrumentTurnoverFeed)getResult(OOUArrayOfInstrumentTurnoverFeed.class,__result,"TurnoverVolumeDealsResult",__envelope);
            }
        },"http://tempuri.org/AtsWebFeedService/TurnoverVolumeDeals",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OOUOperationResult< OOUArrayOfInstrumentTurnoverFeed>> TurnoverVolumeDealsAsync(final java.util.Date FromDate,final java.util.Date ToDate,final String AssetClass,final String SecurityCode,final Integer MarketCode,final Integer DataPeriod)
    {
        return executeAsync(new OOUFunctions.IFunc< OOUArrayOfInstrumentTurnoverFeed>() {
            public OOUArrayOfInstrumentTurnoverFeed Func() throws Exception {
                return TurnoverVolumeDeals( FromDate,ToDate,AssetClass,SecurityCode,MarketCode,DataPeriod);
            }
        },"TurnoverVolumeDeals");
    }
    
    public OOUArrayOfIndicesLivePrice LiveIndexPrices( ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OOUArrayOfIndicesLivePrice)execute(new OOUIWcfMethod()
        {
            @Override
            public OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OOUExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "LiveIndexPrices");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object __result)throws Exception {
                return (OOUArrayOfIndicesLivePrice)getResult(OOUArrayOfIndicesLivePrice.class,__result,"LiveIndexPricesResult",__envelope);
            }
        },"http://tempuri.org/AtsWebFeedService/LiveIndexPrices",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OOUOperationResult< OOUArrayOfIndicesLivePrice>> LiveIndexPricesAsync()
    {
        return executeAsync(new OOUFunctions.IFunc< OOUArrayOfIndicesLivePrice>() {
            public OOUArrayOfIndicesLivePrice Func() throws Exception {
                return LiveIndexPrices( );
            }
        },"LiveIndexPrices");
    }
    
    public OOUArrayOfInstrumentLiveFeed MarketPricesForDateRange(final Integer MarketCode,final java.util.Date FromDate,final java.util.Date ToDate,final String AssetClass,final String SecurityCode,final Integer DataPeriod,final String CountryCode ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OOUArrayOfInstrumentLiveFeed)execute(new OOUIWcfMethod()
        {
            @Override
            public OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OOUExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "MarketPricesForDateRange");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="MarketCode";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(MarketCode!=null?MarketCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="FromDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(FromDate!=null?OOUHelper.getDateTimeFormat().format(FromDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="ToDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ToDate!=null?OOUHelper.getDateTimeFormat().format(ToDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="AssetClass";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(AssetClass!=null?AssetClass:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="SecurityCode";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(SecurityCode!=null?SecurityCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="DataPeriod";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(DataPeriod!=null?DataPeriod:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="CountryCode";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(CountryCode!=null?CountryCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object __result)throws Exception {
                return (OOUArrayOfInstrumentLiveFeed)getResult(OOUArrayOfInstrumentLiveFeed.class,__result,"MarketPricesForDateRangeResult",__envelope);
            }
        },"http://tempuri.org/AtsWebFeedService/MarketPricesForDateRange",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OOUOperationResult< OOUArrayOfInstrumentLiveFeed>> MarketPricesForDateRangeAsync(final Integer MarketCode,final java.util.Date FromDate,final java.util.Date ToDate,final String AssetClass,final String SecurityCode,final Integer DataPeriod,final String CountryCode)
    {
        return executeAsync(new OOUFunctions.IFunc< OOUArrayOfInstrumentLiveFeed>() {
            public OOUArrayOfInstrumentLiveFeed Func() throws Exception {
                return MarketPricesForDateRange( MarketCode,FromDate,ToDate,AssetClass,SecurityCode,DataPeriod,CountryCode);
            }
        },"MarketPricesForDateRange");
    }
    
    public OOUArrayOfInstrumentLiveFeed MarketCapsForDateRange(final Integer MarketCode,final java.util.Date FromDate,final java.util.Date ToDate,final String AssetClass,final String Classification,final String SecurityCode,final Integer DataPeriod,final String CountryCode ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OOUArrayOfInstrumentLiveFeed)execute(new OOUIWcfMethod()
        {
            @Override
            public OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OOUExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "MarketCapsForDateRange");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="MarketCode";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(MarketCode!=null?MarketCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="FromDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(FromDate!=null?OOUHelper.getDateTimeFormat().format(FromDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="ToDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ToDate!=null?OOUHelper.getDateTimeFormat().format(ToDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="AssetClass";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(AssetClass!=null?AssetClass:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="Classification";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(Classification!=null?Classification:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="SecurityCode";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(SecurityCode!=null?SecurityCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="DataPeriod";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(DataPeriod!=null?DataPeriod:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="CountryCode";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(CountryCode!=null?CountryCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object __result)throws Exception {
                return (OOUArrayOfInstrumentLiveFeed)getResult(OOUArrayOfInstrumentLiveFeed.class,__result,"MarketCapsForDateRangeResult",__envelope);
            }
        },"http://tempuri.org/AtsWebFeedService/MarketCapsForDateRange",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OOUOperationResult< OOUArrayOfInstrumentLiveFeed>> MarketCapsForDateRangeAsync(final Integer MarketCode,final java.util.Date FromDate,final java.util.Date ToDate,final String AssetClass,final String Classification,final String SecurityCode,final Integer DataPeriod,final String CountryCode)
    {
        return executeAsync(new OOUFunctions.IFunc< OOUArrayOfInstrumentLiveFeed>() {
            public OOUArrayOfInstrumentLiveFeed Func() throws Exception {
                return MarketCapsForDateRange( MarketCode,FromDate,ToDate,AssetClass,Classification,SecurityCode,DataPeriod,CountryCode);
            }
        },"MarketCapsForDateRange");
    }
    
    public OOUArrayOfBondInformation BondScheduleInformation(final java.util.Date FromDate,final java.util.Date ToDate ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OOUArrayOfBondInformation)execute(new OOUIWcfMethod()
        {
            @Override
            public OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OOUExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BondScheduleInformation");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="FromDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(FromDate!=null?OOUHelper.getDateTimeFormat().format(FromDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="ToDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ToDate!=null?OOUHelper.getDateTimeFormat().format(ToDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object __result)throws Exception {
                return (OOUArrayOfBondInformation)getResult(OOUArrayOfBondInformation.class,__result,"BondScheduleInformationResult",__envelope);
            }
        },"http://tempuri.org/AtsWebFeedService/BondScheduleInformation",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OOUOperationResult< OOUArrayOfBondInformation>> BondScheduleInformationAsync(final java.util.Date FromDate,final java.util.Date ToDate)
    {
        return executeAsync(new OOUFunctions.IFunc< OOUArrayOfBondInformation>() {
            public OOUArrayOfBondInformation Func() throws Exception {
                return BondScheduleInformation( FromDate,ToDate);
            }
        },"BondScheduleInformation");
    }
    
    public OOUArrayOfIndexBasisPointsInformation IndexBasisPointsForDateRange(final java.util.Date FromDate,final java.util.Date ToDate,final String IndexType,final Integer DataPeriod,final Integer MarketCode,final String CountryCode ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OOUArrayOfIndexBasisPointsInformation)execute(new OOUIWcfMethod()
        {
            @Override
            public OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OOUExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "IndexBasisPointsForDateRange");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="FromDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(FromDate!=null?OOUHelper.getDateTimeFormat().format(FromDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="ToDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ToDate!=null?OOUHelper.getDateTimeFormat().format(ToDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="IndexType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(IndexType!=null?IndexType:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="DataPeriod";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(DataPeriod!=null?DataPeriod:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="MarketCode";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(MarketCode!=null?MarketCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="CountryCode";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(CountryCode!=null?CountryCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object __result)throws Exception {
                return (OOUArrayOfIndexBasisPointsInformation)getResult(OOUArrayOfIndexBasisPointsInformation.class,__result,"IndexBasisPointsForDateRangeResult",__envelope);
            }
        },"http://tempuri.org/AtsWebFeedService/IndexBasisPointsForDateRange",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OOUOperationResult< OOUArrayOfIndexBasisPointsInformation>> IndexBasisPointsForDateRangeAsync(final java.util.Date FromDate,final java.util.Date ToDate,final String IndexType,final Integer DataPeriod,final Integer MarketCode,final String CountryCode)
    {
        return executeAsync(new OOUFunctions.IFunc< OOUArrayOfIndexBasisPointsInformation>() {
            public OOUArrayOfIndexBasisPointsInformation Func() throws Exception {
                return IndexBasisPointsForDateRange( FromDate,ToDate,IndexType,DataPeriod,MarketCode,CountryCode);
            }
        },"IndexBasisPointsForDateRange");
    }
    
    public OOUArrayOfInstrumentInformation GetInstrumentInformation( ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OOUArrayOfInstrumentInformation)execute(new OOUIWcfMethod()
        {
            @Override
            public OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OOUExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetInstrumentInformation");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object __result)throws Exception {
                return (OOUArrayOfInstrumentInformation)getResult(OOUArrayOfInstrumentInformation.class,__result,"GetInstrumentInformationResult",__envelope);
            }
        },"http://tempuri.org/AtsWebFeedService/GetInstrumentInformation",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OOUOperationResult< OOUArrayOfInstrumentInformation>> GetInstrumentInformationAsync()
    {
        return executeAsync(new OOUFunctions.IFunc< OOUArrayOfInstrumentInformation>() {
            public OOUArrayOfInstrumentInformation Func() throws Exception {
                return GetInstrumentInformation( );
            }
        },"GetInstrumentInformation");
    }
    
    public OOUArrayOfSectorInformation GetSectorInformation( ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OOUArrayOfSectorInformation)execute(new OOUIWcfMethod()
        {
            @Override
            public OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OOUExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetSectorInformation");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object __result)throws Exception {
                return (OOUArrayOfSectorInformation)getResult(OOUArrayOfSectorInformation.class,__result,"GetSectorInformationResult",__envelope);
            }
        },"http://tempuri.org/AtsWebFeedService/GetSectorInformation",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OOUOperationResult< OOUArrayOfSectorInformation>> GetSectorInformationAsync()
    {
        return executeAsync(new OOUFunctions.IFunc< OOUArrayOfSectorInformation>() {
            public OOUArrayOfSectorInformation Func() throws Exception {
                return GetSectorInformation( );
            }
        },"GetSectorInformation");
    }
    
    public OOUArrayOfIndices GetIndicesInformation( ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OOUArrayOfIndices)execute(new OOUIWcfMethod()
        {
            @Override
            public OOUExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OOUExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetIndicesInformation");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(OOUExtendedSoapSerializationEnvelope __envelope, Object __result)throws Exception {
                return (OOUArrayOfIndices)getResult(OOUArrayOfIndices.class,__result,"GetIndicesInformationResult",__envelope);
            }
        },"http://tempuri.org/AtsWebFeedService/GetIndicesInformation",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OOUOperationResult< OOUArrayOfIndices>> GetIndicesInformationAsync()
    {
        return executeAsync(new OOUFunctions.IFunc< OOUArrayOfIndices>() {
            public OOUArrayOfIndices Func() throws Exception {
                return GetIndicesInformation( );
            }
        },"GetIndicesInformation");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String GetMarketSegments( ) throws Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, OOUOperationResult< String>> GetMarketSegmentsAsync()
    {
        return executeAsync(new OOUFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GetMarketSegments( );
            }
        },"GetMarketSegments");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String GetBlockTransactions(final String fromDate,final String toDate ) throws Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, OOUOperationResult< String>> GetBlockTransactionsAsync(final String fromDate,final String toDate)
    {
        return executeAsync(new OOUFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GetBlockTransactions( fromDate,toDate);
            }
        },"GetBlockTransactions");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String GetInstrumentIndices( ) throws Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, OOUOperationResult< String>> GetInstrumentIndicesAsync()
    {
        return executeAsync(new OOUFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GetInstrumentIndices( );
            }
        },"GetInstrumentIndices");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String GetInstrumentType( ) throws Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, OOUOperationResult< String>> GetInstrumentTypeAsync()
    {
        return executeAsync(new OOUFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GetInstrumentType( );
            }
        },"GetInstrumentType");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String GetTradeDailySummary(final String date,final String CountryCode ) throws Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, OOUOperationResult< String>> GetTradeDailySummaryAsync(final String date,final String CountryCode)
    {
        return executeAsync(new OOUFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GetTradeDailySummary( date,CountryCode);
            }
        },"GetTradeDailySummary");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String GetIndexDailySummary(final String Date,final String CountryCode ) throws Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, OOUOperationResult< String>> GetIndexDailySummaryAsync(final String Date,final String CountryCode)
    {
        return executeAsync(new OOUFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GetIndexDailySummary( Date,CountryCode);
            }
        },"GetIndexDailySummary");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String GetDaysData(final String contract,final String date ) throws Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, OOUOperationResult< String>> GetDaysDataAsync(final String contract,final String date)
    {
        return executeAsync(new OOUFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GetDaysData( contract,date);
            }
        },"GetDaysData");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String GetDaysDeals(final String contract,final String date ) throws Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, OOUOperationResult< String>> GetDaysDealsAsync(final String contract,final String date)
    {
        return executeAsync(new OOUFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GetDaysDeals( contract,date);
            }
        },"GetDaysDeals");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String GetNews(final String fromDate,final String toDate,final String categoryValue ) throws Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, OOUOperationResult< String>> GetNewsAsync(final String fromDate,final String toDate,final String categoryValue)
    {
        return executeAsync(new OOUFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GetNews( fromDate,toDate,categoryValue);
            }
        },"GetNews");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String GetLatestDepth(final String contract ) throws Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, OOUOperationResult< String>> GetLatestDepthAsync(final String contract)
    {
        return executeAsync(new OOUFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GetLatestDepth( contract);
            }
        },"GetLatestDepth");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String GetDailyTrades(final String fromDate,final String toDate ) throws Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, OOUOperationResult< String>> GetDailyTradesAsync(final String fromDate,final String toDate)
    {
        return executeAsync(new OOUFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GetDailyTrades( fromDate,toDate);
            }
        },"GetDailyTrades");
    }

    protected Object execute(OOUIWcfMethod wcfMethod,String methodName,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws Exception
    {
        Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        OOUExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport,profile);
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }

    protected < T> android.os.AsyncTask< Void, Void, OOUOperationResult< T>>  executeAsync(final OOUFunctions.IFunc< T> func, final String methodName)
    {
        return new android.os.AsyncTask< Void, Void, OOUOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected OOUOperationResult< T> doInBackground(Void... params) {
                OOUOperationResult< T> result = new OOUOperationResult< T>();
                try
                {
                    result.MethodName=methodName;
                    result.Result= func.Func();
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(OOUOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }

    protected Exception convertToException(org.ksoap2.SoapFault fault,OOUExtendedSoapSerializationEnvelope envelope)
    {
        org.ksoap2.SoapFault newException = fault;
                return newException;
    }
}


