package com.dsetanzania.dse.helperClasses.livedata_classes;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.7.8
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigDecimal;

public class OOUInstrumentTurnoverFeed extends AttributeContainer implements KvmSerializable
{
    
    public String Classification;
    
    public BigDecimal ClosingPrice;
    
    public Integer Deals;
    
    public String DisplayCode;
    
    public String EquityCode;
    
    public BigDecimal High;
    
    public String ISINNumber;
    
    public String InstrumentDescription;
    
    public String InstrumentTypeCode;
    
    public String InstrumentTypeName;
    
    public BigDecimal Low;
    
    public BigDecimal MarketCapitalisation;
    
    public BigDecimal OpeningPrice;
    
    public BigDecimal SharesInIssue;
    
    public String ShortName;
    
    public java.util.Date TradeDate;
    
    public BigDecimal Turnover;
    
    public BigDecimal Volume;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, OOUExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,OOUExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("Classification"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Classification = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Classification = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ClosingPrice"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ClosingPrice = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.ClosingPrice = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Deals"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Deals = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.Deals = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DisplayCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DisplayCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DisplayCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EquityCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EquityCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.EquityCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("High"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.High = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.High = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ISINNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ISINNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ISINNumber = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("InstrumentDescription"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.InstrumentDescription = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.InstrumentDescription = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("InstrumentTypeCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.InstrumentTypeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.InstrumentTypeCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("InstrumentTypeName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.InstrumentTypeName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.InstrumentTypeName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Low"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Low = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.Low = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MarketCapitalisation"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MarketCapitalisation = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.MarketCapitalisation = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("OpeningPrice"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.OpeningPrice = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.OpeningPrice = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SharesInIssue"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SharesInIssue = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.SharesInIssue = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ShortName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ShortName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ShortName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TradeDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TradeDate = OOUHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.TradeDate = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Turnover"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Turnover = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.Turnover = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Volume"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Volume = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.Volume = (BigDecimal)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Classification!=null?this.Classification:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.ClosingPrice!=null?this.ClosingPrice.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Deals!=null?this.Deals:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.DisplayCode!=null?this.DisplayCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.EquityCode!=null?this.EquityCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.High!=null?this.High.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.ISINNumber!=null?this.ISINNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.InstrumentDescription!=null?this.InstrumentDescription:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.InstrumentTypeCode!=null?this.InstrumentTypeCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.InstrumentTypeName!=null?this.InstrumentTypeName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.Low!=null?this.Low.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.MarketCapitalisation!=null?this.MarketCapitalisation.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.OpeningPrice!=null?this.OpeningPrice.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.SharesInIssue!=null?this.SharesInIssue.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.ShortName!=null?this.ShortName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.TradeDate!=null?OOUHelper.getDateTimeFormat().format(this.TradeDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.Turnover!=null?this.Turnover.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.Volume!=null?this.Volume.toString():SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 18;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Classification";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ClosingPrice";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Deals";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DisplayCode";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "EquityCode";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "High";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ISINNumber";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InstrumentDescription";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InstrumentTypeCode";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InstrumentTypeName";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Low";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MarketCapitalisation";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "OpeningPrice";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SharesInIssue";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ShortName";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TradeDate";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Turnover";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Volume";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
