package com.dsetanzania.dse.helperClasses.livedata_classes;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.7.8
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigDecimal;

public class OOUSecurityLivePrice extends AttributeContainer implements KvmSerializable
{
    
    public String Board;
    
    public BigDecimal Change;
    
    public BigDecimal Close;
    
    public String Company;
    
    public BigDecimal High;
    
    public BigDecimal LastDealPrice;
    
    public Long LastTradedQuantity;
    
    public BigDecimal Low;
    
    public BigDecimal MarketCap;
    
    public BigDecimal OpeningPrice;
    
    public java.util.Date Time;
    
    public Long Volume;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, OOUExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,OOUExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("Board"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Board = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Board = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Change"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Change = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.Change = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Close"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Close = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.Close = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Company"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Company = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Company = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("High"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.High = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.High = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("LastDealPrice"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.LastDealPrice = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.LastDealPrice = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("LastTradedQuantity"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.LastTradedQuantity = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.LastTradedQuantity = (Long)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Low"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Low = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.Low = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MarketCap"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MarketCap = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.MarketCap = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("OpeningPrice"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.OpeningPrice = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.OpeningPrice = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Time"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Time = OOUHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.Time = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Volume"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Volume = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.Volume = (Long)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Board!=null?this.Board:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Change!=null?this.Change.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Close!=null?this.Close.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Company!=null?this.Company:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.High!=null?this.High.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.LastDealPrice!=null?this.LastDealPrice.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.LastTradedQuantity!=null?this.LastTradedQuantity:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.Low!=null?this.Low.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.MarketCap!=null?this.MarketCap.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.OpeningPrice!=null?this.OpeningPrice.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.Time!=null?OOUHelper.getDateTimeFormat().format(this.Time):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.Volume!=null?this.Volume:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Board";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Change";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Close";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Company";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "High";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "LastDealPrice";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "LastTradedQuantity";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Low";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MarketCap";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "OpeningPrice";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Time";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "Volume";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
