package com.dsetanzania.dse;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.7.8
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class OOUIndices extends AttributeContainer implements KvmSerializable
{
    
    public Integer IdIndex;
    
    public String IndexLongName;
    
    public String IndexShortName;
    
    public Integer SegmentId;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, OOUExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,OOUExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("IdIndex"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdIndex = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdIndex = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IndexLongName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IndexLongName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IndexLongName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IndexShortName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IndexShortName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IndexShortName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SegmentId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SegmentId = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.SegmentId = (Integer)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdIndex!=null?this.IdIndex:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.IndexLongName!=null?this.IndexLongName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.IndexShortName!=null?this.IndexShortName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.SegmentId!=null?this.SegmentId:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdIndex";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IndexLongName";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IndexShortName";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "SegmentId";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
