package com.dsetanzania.dse;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.7.8
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface OOUIServiceEvents
{
    void Starting();
    void Completed(OOUOperationResult result);
}
