package com.dsetanzania.dse;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.7.8
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigDecimal;

public class OOUIndexBasisPointsInformation extends AttributeContainer implements KvmSerializable
{
    
    public String DateRange;
    
    public String IndexCode;
    
    public String IndexDescription;
    
    public BigDecimal IndexValue;
    
    public Integer IsActive;
    
    public Long MarketCapitalization;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, OOUExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,OOUExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("DateRange"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DateRange = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DateRange = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IndexCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IndexCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IndexCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IndexDescription"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IndexDescription = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IndexDescription = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IndexValue"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IndexValue = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.IndexValue = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IsActive"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IsActive = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IsActive = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MarketCapitalization"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MarketCapitalization = new Long(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.MarketCapitalization = (Long)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.DateRange!=null?this.DateRange:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.IndexCode!=null?this.IndexCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.IndexDescription!=null?this.IndexDescription:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.IndexValue!=null?this.IndexValue.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.IsActive!=null?this.IsActive:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.MarketCapitalization!=null?this.MarketCapitalization:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateRange";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IndexCode";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IndexDescription";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IndexValue";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IsActive";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "MarketCapitalization";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
