package com.dsetanzania.dse;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.7.8
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigDecimal;

public class OOUInstrumentInformation extends AttributeContainer implements KvmSerializable
{
    
    public java.util.Date CreatedOn;
    
    public String CurrencyCode;
    
    public BigDecimal DaysClose;
    
    public String ISIN;
    
    public Integer IdInstrument;
    
    public Integer IdInstrumentType;
    
    public Integer IdSector;
    
    public Integer IdSegment;
    
    public String InstrumentCode;
    
    public String InstrumentName;
    
    public Double InterestRate;
    
    public java.util.Date MaturityDate;
    
    public String Status;
    
    public Boolean Suspended;
    
    public Boolean Tradable;
        
    private transient Object __source;
    

    
    
    public void loadFromSoap(Object paramObj, OOUExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,OOUExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("CreatedOn"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CreatedOn = OOUHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.CreatedOn = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CurrencyCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CurrencyCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CurrencyCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DaysClose"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DaysClose = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.DaysClose = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ISIN"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ISIN = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ISIN = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdInstrument"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdInstrument = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdInstrument = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdInstrumentType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdInstrumentType = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdInstrumentType = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdSector"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdSector = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdSector = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdSegment"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdSegment = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdSegment = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("InstrumentCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.InstrumentCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.InstrumentCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("InstrumentName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.InstrumentName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.InstrumentName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("InterestRate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.InterestRate = new Double(j.toString());
                    }
                }
                else if (obj instanceof Double){
                    this.InterestRate = (Double)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MaturityDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MaturityDate = OOUHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.MaturityDate = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Status"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Status = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Status = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Suspended"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Suspended = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.Suspended = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Tradable"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Tradable = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.Tradable = (Boolean)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.CreatedOn!=null?OOUHelper.getDateTimeFormat().format(this.CreatedOn):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.CurrencyCode!=null?this.CurrencyCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.DaysClose!=null?this.DaysClose.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.ISIN!=null?this.ISIN:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.IdInstrument!=null?this.IdInstrument:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.IdInstrumentType!=null?this.IdInstrumentType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.IdSector!=null?this.IdSector:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.IdSegment!=null?this.IdSegment:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.InstrumentCode!=null?this.InstrumentCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.InstrumentName!=null?this.InstrumentName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.InterestRate!=null?this.InterestRate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.MaturityDate!=null?OOUHelper.getDateTimeFormat().format(this.MaturityDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.Status!=null?this.Status:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.Suspended!=null?this.Suspended:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.Tradable!=null?this.Tradable:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 15;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CreatedOn";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CurrencyCode";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DaysClose";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ISIN";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdInstrument";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdInstrumentType";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdSector";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdSegment";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InstrumentCode";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InstrumentName";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==10)
        {
            info.type = Double.class;
            info.name = "InterestRate";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MaturityDate";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Status";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "Suspended";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "Tradable";
            info.namespace= "http://schemas.datacontract.org/2004/07/FeedWebService";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}
